routes/clientes.py
from flask import Blueprint, render_template, request
from databases.models.cliente import Cliente
import bcrypt

clientes_route = Blueprint("clientes", __name__)
"""
/clientes/ - (GET) - Listar cliente
/clientes/ - (POST) - Adicionar um cliente
/clientes/new - (GET) - Formulario para criação de um cliente
/clientes/<id> - (GET) - Obter dados de um cliente
/clientes/<id>/edit -(GET) - Renderizar um formulario para editar um cliente
/clientes/<id>/update - (PUT) - Atualizar os dados de um cliente
/clientes/<id>/delete - (DELETE) - deleta o registro do usuário
"""
@clientes_route.route('/')
def lista_cliente():
    """ Listar os clientes"""
    clientes = Cliente.select()
    return render_template("lista_clientes.html",clients=clientes)

@clientes_route.route('/', methods=['POST'])
def inserir_cliente():
    """ inserir dados cliente"""
    data = request.json
    novo_usuario = Cliente.create(
        nome = data['nome'],
        email = data['email'],
    )

    clients.append(novo_usuario)
    cliente = novo_usuario
    return render_template("item_cliente.html", cliente=cliente )

@clientes_route.route('/new', methods=['GET'])
def form_cliente():
    """Exibir formulario para adicionar novo cliente"""
    return render_template("form_cliente.html")


@clientes_route.route('/<int:client_id>')
def detalhe_cliente(client_id):
    """EXIBIR DADOS DE UM CLIENTE"""
    return render_template("detalhe_cliente.html")
    
@clientes_route.route('/<int:client_id>/edit')
def form_edit_cliente(client_id):
    """Formulário para editar um cliente"""
    cliente = None
    cliente = Cliente.get_by_id(client_id)
    return render_template("form_edit_cliente.html", cliente=cliente)

@clientes_route.route('/<int:client_id>/update', methods=['PUT'])
def update_cliente(client_id):
    #Obter dados do usuário pelo formulario
    data = request.json
    #obter usuário pelo ID
    pessoa = Cliente.get_by_id(client_id)
    pessoa.nome = data['nome']
    pessoa.email = data['email']
    pessoa.save()

    return render_template('item_cliente.html', cliente=pessoa)


@clientes_route.route('/<int:client_id>/delete', methods=['DELETE'])
def delete_cliente(client_id):
    """Deletar Cliente"""
    cliente = Cliente.get_by_id(client_id)
    cliente.delete_instance()

    return {'delete':'ok'}


@clientes_route.route('/<int:client_id>/delete', methods=['POST'])
def subir_imagem():
    return '' 

routes/encurtador.py
from flask import Blueprint, redirect, render_template,request, flash
from databases.models.links import Link
from peewee import DoesNotExist
import requests
encurtador =  Blueprint('encurtador', __name__)

class StatusCodeError(Exception):
    """Custom exception for handling non-200 status codes."""
    def __init__(self, status_code):
        self.status_code = status_code
        super().__init__(f"Status code was {status_code}")

@encurtador.route('/', methods=['GET','POST'])
def inicial():
    return render_template('encurtador.html')


@encurtador.route('/link', methods=['POST'])
def link():
    data = request.form
    idlink = None
    linkk = data['Linkenc']
    if not linkk.startswith("https://"):
        linkk = "https://" + linkk
    else:
        pass
    try:
        linkk = linkk.strip().lower()
        link_record = Link.get(Link.link == linkk)
        idlink = link_record.id
    except:
        pass
    if idlink:
        flash(idlink, 'id')
    else:
         try:
            acessar = requests.get(url=linkk)
            if acessar.status_code != 200:
                raise StatusCodeError(acessar.status_code)
            else:
                Link.create(link=linkk)
                flash('Salvo com sucesso', 'success')
    # Link.create(link=linkk)
         except requests.exceptions.MissingSchema as e:
                flash(f"{e}", 'error')
         except StatusCodeError as e:
                flash(f"{e}", 'error')
         except requests.exceptions.RequestException as e:
                # Handle other requests exceptions if needed
                flash(f"{e}", 'error')
    return redirect('/enc/')

@encurtador.route('/<int:id>')
def linkencurtado(id):
    link1 = Link.get_by_id(id)
    return redirect(link1.link)

templates/cadastro.html
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Página de Cadastro</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/cadastro.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <img src="{{url_for('static', filename='images/brain.svg')}}" class="brain_img" alt="Brain">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="main">
        <div class="titulo"><h1>CADASTRO</h1></div>
        <div class="form-cad">
            <form action="/cadastrar" method="POST" id="form-1">
            <div class="user">   
            <Label>User</Label>
            <input type="text" placeholder="usuário" id="user" name='user'>
            </div>
            <div class="email">
            <label>E-mail</label>
            <input type="email" aria-describedby="emailHelp" placeholder="email@mail.com" id="email" name='email' required>
            </div>
            <div class="password">
            <label>Password</label>
            <INPUt type="password" placeholder="password" id="pass" name="pass1" required>
            </div>

            <div class="password2">
            <label>Repita a senha</label>
            <input type="password" id="passr" placeholder='password' name='pass2' required>
            </div>
            <div class="btn-cdn">
            <button class="btn btn-primary" id=btn-cadastro>Cadastrar</button> 
            </div>
            {% set success = get_flashed_messages(category_filter=['success']) %}
            {% if success %}
              <h6 style="color: green;">{{success[0]}}</h6>
            {% endif %}
            {%set error = get_flashed_messages(category_filter=['error'])%}
            {% if error %}
            <h6 style="color: red;">{{error[0]}}</h6>
            {% endif %}
        </form>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/encurtador.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Encurtador</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/encurtador.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
      <form action="{{url_for('encurtador.link')}}" method="POST" class="form">
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Example label</label>
                {% set id = get_flashed_messages(category_filter=['id']) %}
                <input type="text" class="form-control" id="Linkenc" placeholder="Example input placeholder" name="Linkenc"
                       value="{% if id %}127.0.0.1/enc/{{ id[0] }}{% endif %}">

                {%set success = get_flashed_messages(category_filter=['success'])%}
                {%if success%}
                  <h6 style="color: green;">{{success[0]}}</h6>
                {% endif %}
                {%set error = get_flashed_messages(category_filter=['error'])%}
                {% if error %}
                  <h6 style="color: red;">{{error[0]}}</h6>
                {% endif %}
            </div>
          <button type="submit" class="btn btn-primary" id="butaum">Criar</button>
        </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/form_cliente.html
<form class="c-form" 
action="{{ url_for('clientes.inserir_cliente') }}" 
method="POST"
c-append="#lista-cliente">
    <div class="mb-3">
      <label class="form-label" id="form_name_label">Nome</label>
      <input type="text" class="form-control" name="nome" id="form_name">
    </div>
    <div class="mb-3">
        <label class="form-label">E-mail</label>
        <input type="email" class="form-control" name="email">
      </div>  
      <button class="btn btn-primary">Criar Usuário</button>
  </form>

templates/form_edit_cliente.html
<form class="c-form" 
{% if cliente %}
    action="{{ url_for('clientes.update_cliente', client_id=cliente.id) }}" 
{% else %}
    action="{{ url_for('clientes.inserir_cliente') }}" 
{% endif %}

method="{%if cliente %}PUT{% else %}POST{% endif %}"

{% if cliente %} c-swap="#cliente-{{cliente.id}}"{% endif %}>
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome"{% if cliente %} value={{cliente.nome}} {%endif%}>
    </div>
    <div class="mb-3">
        <label class="form-label">E-mail</label>
        <input type="email" class="form-control" name="email"{% if cliente %}value={{cliente.email}}{%endif%}>
      </div>  
      <button class="btn btn-primary">{% if cliente %} Salvar {% else %} Criar {% endif %}</button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello world</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
  </head>
  <body>
    <div id="contan" class="container">
    
    <!--Formulario add cliente-->
    <div c-container="{{url_for('clientes.form_cliente')}}" id="gerenciar-user"></div>
        <hr>
    
        <h2>Lista de Clientes</h2>
    <!--Lista de Clientes -->
    <div c-container="{{ url_for('clientes.lista_cliente')}}"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/cru.js') }}"></script>
    </body>
</html>

templates/item_cliente.html
<tr id="cliente-{{cliente.id}}">
    <th scope="row">{{cliente.id}}</th>
    <td>{{cliente.nome}}</td>
    <td>{{cliente.email}}</td>
    <td>
        <button class="btn btn-primary"
        c-get="{{url_for('clientes.form_edit_cliente', client_id=cliente.id) }}"
        c-target="#gerenciar-user">
        Editar</button>
        <button class="btn btn-danger" c-delete="{{url_for('clientes.delete_cliente', client_id=cliente.id)}}"
        c-remove-closest="tr">
        Deletar</button>
        <button class="btn btn-success"data-bs-toggle="modal" data-bs-target="#VER-OBJECT">VER</button>

        
    </td>
</tr>

templates/lista_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">{{clients.id}}</th>
        <th scope="col">Nome</th>
        <th scope="col">E-mail</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista-cliente">
        {%for cliente in clients%}
          {%  include 'item_cliente.html' %}
        {% endfor %}
    </tbody>
  </table>

</dvi>

templates/login.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PÁGINA DE LOGIN</title>
    <img src="{{url_for('static', filename='images/Carro.svg')}}" alt="Carro" class="left-img">
    <link rel="stylesheet" href="{{url_for('static', filename='css/login.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
  </head>
  <body>
    <a class="btn btn-primary" href="/cadastro" role="button" id="btn-cad">Cadastrar</a>
      <div class="div-right">
      <h1 class="title">LOGIN PAGE</h1>
      <div class="form-div">
        <form id='formu' action="/logar" method="POST">
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">USER</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nome de Usuário" name="user">
              <div id="emailHelp" class="form-text"></div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Senha" name="pass">
            </div>
            <button type="submit" id='btn-login' class="btn btn-primary">Login</button>
          </form>
          {%set sucess = get_flashed_messages(category_filter=['success'])%}
          {%if sucess %}
            <h6 style="color: green;">{{sucess[0]}}</h6>
          {% endif %}
          {%set error = get_flashed_messages(category_filter=['error'])%}
          {%if error %}
            <h6 style="color: red;">{{error[0]}}</h6>
          {% endif %}

      </div>
      </div> 
      
      <div class="div-left"></div> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/profile.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
  </head>
  <body>
    <div class="profile">
        <div class="profile_img" id="profile_image"><img class='img' src="{{url_for('static', filename='images/brain.svg')}}" alt="perfil.svg"><input id="input-img" class="input-img" type="file"></div>
        <div class="profile_name" id="profile-name"><h3>Nome: {{nome}}</h3></div>
        <div class="profile_email"><h6>Email: {{email}}</h6></div>
        <div class="profile_permissao"><h6>Permissao do usuario: {{permissoes}}</h6></div>

        <div><form action="/subir-imagem">
        
        </form></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/script.js')}}"></script>
  </body>
</html>